export function signupData(data){
  return {
    name: data.name,
    email: data.email,
    password: data.password,
    confirmPassword: data.password,
    confirm_password: data.password,
    cpassword: data.password,
    password_confirmation: data.password,
    passwordConfirm: data.password,
    confirmPass: data.password,
    passwordVerify: data.password,
    verifyPassword: data.password,
    ConfirmPassword: data.password,
    Confirm_Password: data.password,
    confirm_password_: data.password,
    Confirm_Pass: data.password,
    ConfirmPass: data.password,
    c_pass: data.password,
    cpass: data.password,
    cpwd: data.password,
    cp: data.password,
    password_retype: data.password,
    pass_confirm: data.password,
    re_password: data.password,
    repeatPassword: data.password,
    password_repeat: data.password,
    matchPassword: data.password,
    passwordMatch: data.password,
    password_check: data.password,
    passwordConfirmField: data.password,
    retype_password: data.password,
    passwordRetype: data.password,
    role: data.role,
  };
}